version: '3.9'

services:
  search_api:
    image: collaborator_search
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://host.docker.internal:3306/refeitorio
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root